# Generated by Django 3.0.3 on 2020-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_auto_20200203_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poolservices',
            old_name='timestampt',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='poolservices',
            name='state',
            field=models.CharField(choices=[('SA', 'STATE_AVAILABLE'), ('SP', 'STATE_PENDING'), ('SB', 'STATE_BUSY')], default='SA', max_length=50),
        ),
    ]
