# Generated by Django 3.0.3 on 2020-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_auto_20200205_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolservices',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
