# Generated by Django 3.0.3 on 2020-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_auto_20200208_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolservices',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
